complete -c chrome-shell -f
complete -c chrome-shell -n "__fish_use_subcommand" -f -a "run" -d "Run server"
complete -c chrome-shell -n "__fish_use_subcommand" -f -a "install" -d "Install manifest and register specified extensions"
complete -c chrome-shell -n "__fish_use_subcommand" -f -a "uninstall" -d "Uninstall manifest"
complete -c chrome-shell -l target -x -a "chrome" -d "Chrome"
complete -c chrome-shell -l target -x -a "chrome-dev" -d "Chrome Dev"
complete -c chrome-shell -l target -x -a "chrome-beta" -d "Chrome Beta"
complete -c chrome-shell -l target -x -a "chrome-canary" -d "Chrome Canary"
complete -c chrome-shell -l target -x -a "chromium" -d "Chromium"
complete -c chrome-shell -l target -x -d "Specifies the target platform"
complete -c chrome-shell -s v -d "Increases the level of verbosity (the max level is -vvv)"
complete -c chrome-shell -l log -r -F -d "Specifies the file to use for logging"
complete -c chrome-shell -s h -l help -d "Show this help"
complete -c chrome-shell -s V -l version -d "Show version"
